spring.application.name=expensetracker

server.port=${port:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/expense_tracker_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

logging.level.org.springframework.web=trace
logging.level.org.springframework.security=trace